server:
  port: 8085
hm:
  db:
    database: hm-trade
  swagger:
    title: "黑马商场商品服务接口文档"
    packa ge: com.hmall.trade.controller
spring:
  rabbitmq:
    host: 192.168.1.144
    port: 5672
    virtual-host: /jinyubo
    username: jinyubo
    password: jinyubo